

import "@/public/assets/css/responsive.css";
import '@/public/assets/css/style.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import { Manrope } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';

import downAngleIcon from "@/public/assets/images/icons/angle-down.svg";
import bellIcon from "@/public/assets/images/icons/bell.svg";
import logoutIcon from "@/public/assets/images/icons/logout.svg";
import searchIcon from "@/public/assets/images/icons/search.svg";
import analyticsIcon from "@/public/assets/images/icons/sidebar/analytics.svg";
import calendarIcon from "@/public/assets/images/icons/sidebar/calendar.svg";
import customerIcon from "@/public/assets/images/icons/sidebar/customer.svg";
import dashboardIcon from "@/public/assets/images/icons/sidebar/dashboard.svg";
import earningsIcon from "@/public/assets/images/icons/sidebar/earnings.svg";
import expensesIcon from "@/public/assets/images/icons/sidebar/expense.svg";
import leadsIcon from "@/public/assets/images/icons/sidebar/leads.svg";
import projectIcon from "@/public/assets/images/icons/sidebar/project.svg";
import logo from "@/public/assets/images/logo.svg";
import avatar2 from "@/public/uploads/users/avatar-2.png";
import Bootstrap from './lib/bootstrapjs';
import { Providers } from './redux/provider';

const manrope = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={manrope.className}>
        <Providers>
          <main className="root-main-wrapper">

            <aside className="sidebar-wrap custom-scroll-bar">

              <div className="logo-box">
                <Link href="/dashboard">
                  <Image src={logo} alt='logo' />
                </Link>
              </div>

              <div className="side-navbar-wrap">
                <ul className="side-nav">
                  <li className="side-item">
                    <Link href="/dashboard" className="> side-link"><Image src={dashboardIcon} alt="dashboard icon" />
                      Dashboard
                    </Link>
                  </li>
                  <li className="side-item"><Link href="/analytics" className=" side-link"><Image src={analyticsIcon} alt="dashboard icon" />
                    Analytics
                  </Link>
                  </li>
                  <li className="side-item"><Link href="/customer" className="side-link"><Image src={customerIcon} alt="dashboard icon" />Customer</Link>
                  </li>
                  <li className="side-item">
                    <Link href="to-do-list" className=" side-link">

                      <Image src={calendarIcon} alt="dashboard icon" />
                      To Do List
                    </Link>
                  </li>
                  <li className="side-item"><Link href="/projects" className=" side-link"><Image src={projectIcon} alt="dashboard icon" /> Project</Link></li>
                  <li className="side-item side-subitem">
                    <Link className="side-link" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false"
                      aria-controls="collapseExample">
                      <Image src={leadsIcon} alt="dashboard icon" /> Leads

                      <Image src={downAngleIcon} alt="icn" />

                    </Link>
                    <div className="collapse" id="collapseExample">
                      <ul className="sub-nav">
                        <li><Link href="/leads" className="sub-link ">Hosting Leads</Link></li>
                        <li><Link href="/leads-view" className="sub-link ">Marketing Leads</Link></li>
                        <li><Link href="/leads" className="sub-link">Project Leads</Link></li>
                        <li><Link href="/leads" className="sub-link">Website Leads</Link></li>
                        <li><Link href="/lost-leads" className="sub-link">Lost Leads</Link></li>
                      </ul>
                    </div>
                  </li>
                  <li className="side-item side-subitem">
                    <Link className="side-link" data-bs-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false"
                      aria-controls="collapseExample2">
                      <Image src={earningsIcon} alt="dashboard icon" /> Earning
                      <Image src={downAngleIcon} alt="icn" />
                    </Link>
                    <div className="collapse  " id="collapseExample2">
                      <ul className="sub-nav">
                        <li><Link href="/earning " className="sub-link active">Total</Link></li>
                        <li><Link href="/earning" className="sub-link">Hosting</Link></li>
                        <li><Link href="/earning" className="sub-link">Marketing</Link></li>
                        <li><Link href="/earning" className="sub-link">Website</Link></li>
                        <li><Link href="/earning" className="sub-link">Project</Link></li>
                      </ul>
                    </div>
                  </li>
                  <li className="side-item"><Link href="expense" className="side-link ">
                    <Image src={expensesIcon} alt="dashboard icon" /> Expenses</Link>
                  </li>
                  <li className="side-item">
                    <Link href="/logout" className="side-link">
                      <Image src={logoutIcon} alt="a" />
                      Logout
                    </Link>
                  </li>
                </ul>
              </div>

            </aside>

            <header className="header-area">

              <div className="header-search-box">
                <Image src={searchIcon} alt="S" className="img-fluid search" />
                <input type="text" className="form-control" placeholder="Search" />
              </div>

              <div className="header-icons-box">
                <ul className="main">
                  <li className="head-item">
                    <Link href="#" className="head-link">
                      <span></span>
                      <Image src={bellIcon} alt="dashboard icon" />
                    </Link>
                  </li>
                  <li className="head-item">
                    <div className="dropdown p-0 header-dropdown">
                      <Link className="p-0 user head-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <Image src={avatar2} alt="user avatar" />

                      </Link>

                      <ul className="dropdown-menu">
                        <li>
                          <Link className="dropdown-item" href="profile">
                            Profile
                          </Link>
                        </li>
                        <li>
                          <Link className="dropdown-item " href="profile-edit">
                            Profile Setting
                          </Link>
                        </li>
                      </ul>
                    </div>
                  </li>
                  <li className="head-item">
                    <Link href="#" className="d-lg-none head-link" id="menuToggle">
                      <i className="fas fa-bars"></i>
                    </Link>
                  </li>
                </ul>
              </div>

            </header>

            {children}

          </main>
        </Providers>

        <Bootstrap />
      </body>
    </html>
  )
}